# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BhoFBzvmVckqfE5C4C0iOZeyXF5euRpX

# import libraries
"""

from bs4 import BeautifulSoup
import requests
import csv

URL = "https://cars.kg/offers/?vendor=57fa24ee2860c45a2a2c08b0"
r = requests.get(URL)
html = r.text
soup = BeautifulSoup(html,"lxml")
soup.find("span",class_="catalog-item-caption").text.strip()
soup.find("span",class_= "catalog-item-price").text.strip()
soup.find("img",class_= "catalog-item-cover-img").get("src")

for tag in  soup.find_all("span",class_="catalog-item-caption"):
  print(tag.text)

for imag in soup.find_all("img",class_= "catalog-item-cover-img"):
  print(imag.get("src"))

# soup.find("div",class_= "catalog-paginator").text.strip()
for tag in  soup.find_all("div",class_="catalog-paginator"):
  print(tag.text.strip())
# for tag in  soup.find_all("a",class_="pages-item"):
#   print(tag.text.strip())

# soup.find("span",class_= "catalog-item-price").text.strip()
for tag in  soup.find_all("span",class_="catalog-item-price"):
  print(tag.text)

"""# parsing

"""

def write_headers() -> None:
    with open('cars.csv', 'w', newline='') as csvfile:
        fieldnames = ['title', 'price', 'image']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()

def write_to_csv(data: dict) -> None:
    with open('cars.csv', 'a', newline='') as csvfile:
      fieldnames = ['title', 'price', 'image']
      writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
      writer.writerow(data)

URL = "https://cars.kg/offers/?vendor=57fa24ee2860c45a2a2c08b0"

def get_response(url:str)->str:
  response = requests.get(url)
  return response.text

html = get_response(URL)

def get_data(html: str) -> None:
  soup = BeautifulSoup(html, "lxml")
  catalog = soup.find("div", class_="main catalog")
  a_tags = catalog.find_all("a", class_="catalog-list-item")
  for a_tag in a_tags:
    try:
      title = a_tag.find("span", class_="catalog-item-caption").text.strip()
    except AttributeError:
      title = "No title"
    try :
      image = a_tag.find("img", class_="catalog-item-cover-img").get("src")
    except AttributeError:
      image = "https://www.seat.com.mt/content/dam/public/seat-website/carworlds/compare/default-image/ghost.png"
    try:
      price = a_tag.find("span", class_="catalog-item-price").text.strip()
    except AttributeError:
      price = "Договорная"
    
    data = {
        "title": title,
        "price": price,
        "image": image
    }
    write_to_csv(data)


def get_last_page(html: str) -> int:
  soup = BeautifulSoup(html, "lxml")
  pages = soup.find_all('a', class_="pages-item")
  last_page = pages[-2].text
  return int(last_page)

def main(URL: str) -> None:
  write_headers()
  html = get_response(URL)
  last_page = get_last_page(html)
  for page in range(1, last_page+1):
    url = f"https://cars.kg/offers/{page}?vendor=57fa24ee2860c45a2a2c08b0"
    current_page_html = get_response(url)
    get_data(current_page_html)

URL = "https://cars.kg/offers/?vendor=57fa24ee2860c45a2a2c08b0"
main(URL)

from google.colab import drive
drive.mount('/content/drive')

# write_headers()
# get_data(html)